### ISSUE TITLE
ffmpeg,numpy,opencv version

### ISSUE THREAD

**Issue by grafana2018** [djx339/docker-python-opencv-ffmpeg#1]
How i can check ffmpeg,numpy,opencv version insider docker containter?

**Comment by zkailinzhang** [comment]
@grafana2018 , do you have any answers about this question?

**Comment by djx339** [comment]
@grafana2018 @grafana2018 
You can view the codec version, OpenCV version and the detailed OpenCV build information by command inside container:

```shell
python -c "import cv2; print(cv2.getBuildInformation())"
```

 numpy version via `pip freeze`
